version: '3'

services:
  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=spot2gether
      - MONGO_INITDB_ROOT_PASSWORD=spot2gether

  backend:
    image: node:alpine
    restart: always
    expose:
      - 3000
    volumes:
      - ./backend/:/home/node/app/backend/
      - ./helpers/:/home/node/app/helpers/
    working_dir: /home/node/app/backend
    environment:
      - NODE_ENV=production
    command: sh -c 'npm i && nodejs --unhandled-rejections=warn-with-error-code --trace-warnings index.mjs'
    links:
      - mongodb
    depends_on:
      - mongodb

  frontend:
    image: node:16-alpine
    volumes:
      - ./frontend/:/home/node/app/frontend/
    working_dir: /home/node/app/frontend
    command: sh -c 'npm i --include=dev && npm run serve'

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist/:/var/www/html/
    ports:
      - "8083:8080"
    links:
      - backend
      - frontend
    depends_on:
      - backend
      - frontend
